package javaapplication2;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class issue_frame extends javax.swing.JFrame {
  
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String StudentID, BookID;
    LocalDate date = LocalDate.now();
    
    public issue_frame() {
        setIcon();
        initComponents();
        conn = DBConnect.ConnecrDb();
        StudentID = "";
        BookID = "";
        jlblDate.setText( new SimpleDateFormat("dd / MM / yyyy").format(new Date()) );
        setTitle("Issue Book");
    }
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtBookID = new javax.swing.JTextField();
        jlblDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtCampus = new javax.swing.JTextField();
        jtxtCourse = new javax.swing.JTextField();
        jtxtGuardian = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtStudentID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtStock = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtBookYear = new javax.swing.JTextField();
        jtxtAuthor = new javax.swing.JTextField();
        jtxtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtSem = new javax.swing.JTextField();
        jtxtYear = new javax.swing.JTextField();
        jtxtEdition = new javax.swing.JTextField();
        jbtnSearch1 = new javax.swing.JButton();
        jbtnSearch2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jbnIssue = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 30, 117));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtBookID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtBookID.setHighlighter(null);
        jtxtBookID.setVerifyInputWhenFocusTarget(false);
        jtxtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBookIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 140, 30));

        jlblDate.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jlblDate.setForeground(new java.awt.Color(255, 209, 18));
        jlblDate.setText("ymmdy");
        jPanel1.add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 210, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 209, 18));
        jLabel8.setText("STUDENT DETAILS...");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 209, 18));
        jLabel7.setText("BOOK DETAILS....");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jtxtCampus.setEditable(false);
        jtxtCampus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtCampus.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, 30));

        jtxtCourse.setEditable(false);
        jtxtCourse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtCourse.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));

        jtxtGuardian.setEditable(false);
        jtxtGuardian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtGuardian.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtGuardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 30));

        jtxtName.setEditable(false);
        jtxtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtName.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 30));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtStudentID.setVerifyInputWhenFocusTarget(false);
        jtxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 209, 18));
        jLabel19.setText("Semester");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 209, 18));
        jLabel18.setText("Year");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 209, 18));
        jLabel16.setText("Course");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 209, 18));
        jLabel17.setText("Campus");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 209, 18));
        jLabel15.setText("Guardian");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 209, 18));
        jLabel14.setText("Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        jtxtStock.setEditable(false);
        jtxtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtStock.setVerifyInputWhenFocusTarget(false);
        jtxtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 200, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 209, 18));
        jLabel13.setText("Student ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        jtxtBookYear.setEditable(false);
        jtxtBookYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtBookYear.setVerifyInputWhenFocusTarget(false);
        jtxtBookYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBookYearActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtBookYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 200, 30));

        jtxtAuthor.setEditable(false);
        jtxtAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtAuthor.setVerifyInputWhenFocusTarget(false);
        jtxtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 200, 30));

        jtxtTitle.setEditable(false);
        jtxtTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtTitle.setVerifyInputWhenFocusTarget(false);
        jtxtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTitleActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 200, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 209, 18));
        jLabel5.setText("Year");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 209, 18));
        jLabel6.setText("Stock");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 120, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 209, 18));
        jLabel4.setText("Author");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 209, 18));
        jLabel3.setText("Edition");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 209, 18));
        jLabel2.setText("Title");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 46, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 209, 18));
        jLabel1.setText("Book ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jtxtSem.setEditable(false);
        jtxtSem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtSem.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 200, 30));

        jtxtYear.setEditable(false);
        jtxtYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtYear.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jtxtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, 30));

        jtxtEdition.setEditable(false);
        jtxtEdition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtEdition.setVerifyInputWhenFocusTarget(false);
        jtxtEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEditionActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 200, 30));

        jbtnSearch1.setBackground(new java.awt.Color(255, 209, 18));
        jbtnSearch1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnSearch1.setForeground(new java.awt.Color(255, 204, 153));
        jbtnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/loupe.png"))); // NOI18N
        jbtnSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSearch1MouseClicked(evt);
            }
        });
        jbtnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearch1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 51, 30));

        jbtnSearch2.setBackground(new java.awt.Color(255, 209, 18));
        jbtnSearch2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnSearch2.setForeground(new java.awt.Color(255, 204, 153));
        jbtnSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/loupe.png"))); // NOI18N
        jbtnSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSearch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSearch2MouseClicked(evt);
            }
        });
        jbtnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearch2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 51, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 209, 18));
        jLabel9.setText("Date of Issue:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 160, -1));

        jbnIssue.setBackground(new java.awt.Color(255, 209, 18));
        jbnIssue.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbnIssue.setForeground(new java.awt.Color(255, 4, 0));
        jbnIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/5597026(1).png"))); // NOI18N
        jbnIssue.setText("Issue");
        jbnIssue.setBorder(null);
        jbnIssue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnIssueActionPerformed(evt);
            }
        });
        jPanel1.add(jbnIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 200, 70));

        jButton3.setBackground(new java.awt.Color(255, 209, 18));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 4, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/5839091(1).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 200, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        main_frame ob = new main_frame();
        ob.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearch1ActionPerformed
        if ( jtxtStudentID.getText().isEmpty() || jtxtStudentID.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "The fields cannot be left blank.", "Message" , JOptionPane.INFORMATION_MESSAGE);
             }
        else{
             try{
                ResultSet rs;
                PreparedStatement ps = conn.prepareStatement("select * from student where StudentID=?; ");
                ps.setString(1, jtxtStudentID.getText());
                rs = ps.executeQuery();
                
                while(true){
                    if (rs.next()){
                        StudentID = rs.getString("StudentID");
                        jtxtName.setText( rs.getString("Name") );
                        jtxtGuardian.setText( rs.getString("Guardian") );
                        jtxtCourse.setText( rs.getString("Course") );
                        jtxtCampus.setText( rs.getString("Campus") );
                        jtxtYear.setText( rs.getString("Year") );
                        jtxtSem.setText( rs.getString("Semester") );
                        break;    
                    }
                    else{
                        jtxtName.setText( "" );
                        jtxtGuardian.setText( "" );
                        jtxtCourse.setText( "" );
                        jtxtCampus.setText( "" );
                        jtxtYear.setText( "" );
                        jtxtSem.setText( "" );
                        JOptionPane.showMessageDialog(null, "StudentID Does not Exist.", "Message" , JOptionPane.INFORMATION_MESSAGE);
                        jtxtStudentID.setText("");
                        break;
                    }
                }
             
            } catch(Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_jbtnSearch1ActionPerformed
             }
    private void jbnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnIssueActionPerformed
        if ( jtxtStudentID.getText().isEmpty() || jtxtBookID.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "The fields cannot be left blank.", "Message" , JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            try{
            
                String date = new SimpleDateFormat("yyMMdd").format(new Date());
                
                PreparedStatement ps = conn.prepareStatement("insert into record values(?,?,?,null); ");
                ps.setString(1, StudentID);
                ps.setString(2, BookID);
                ps.setString(3, date);
                ps.execute();
                
                ps = conn.prepareStatement("update book set Stock = Stock-1 where BookID = ?; ");
                ps.setString(1, BookID);
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Book has been Issued.", "Message" , JOptionPane.INFORMATION_MESSAGE);
                
            }
            catch(Exception e) { 
                e.printStackTrace(); 
                JOptionPane.showMessageDialog(null, e.getMessage(), "Message" , JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jbnIssueActionPerformed

    private void jtxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentIDActionPerformed

    private void jtxtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockActionPerformed

    private void jtxtBookYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBookYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBookYearActionPerformed

    private void jtxtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAuthorActionPerformed

    private void jtxtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTitleActionPerformed

    private void jtxtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBookIDActionPerformed

    private void jbtnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSearch1MouseClicked
         
    }//GEN-LAST:event_jbtnSearch1MouseClicked

    private void jtxtEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEditionActionPerformed

    private void jbtnSearch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSearch2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSearch2MouseClicked

    private void jbtnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearch2ActionPerformed
         if ( jtxtBookID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "The fields cannot be left blank.", "Message" , JOptionPane.INFORMATION_MESSAGE);
             }
             
        else{
             try{
                ResultSet rs;
                PreparedStatement ps = conn.prepareStatement("select * from book where BookID=?; ");
                ps.setString(1, jtxtBookID.getText());
                rs = ps.executeQuery();
                
                while(true){
                    if (rs.next()){
                        BookID = rs.getString("BookID");
                        jtxtTitle.setText( rs.getString("Title") );
                        jtxtEdition.setText( rs.getString("Edition") );
                        jtxtAuthor.setText( rs.getString("Author") );
                        jtxtBookYear.setText( rs.getString("Year") );
                        jtxtStock.setText( rs.getString("Stock") );
                        jlblDate.setText( rs.getString("DateofIssue") );
                        break;    
                    }
                    else{
                        jtxtTitle.setText("");
                        jtxtEdition.setText("");
                        jtxtAuthor.setText("");
                        jtxtBookYear.setText("");
                        jtxtStock.setText("");
                        JOptionPane.showMessageDialog(null, "BookID Does not Exist.", "Message" , JOptionPane.INFORMATION_MESSAGE);
                        jtxtBookID.setText("");
                        break;
                    }
                }
             
            } catch(Exception e) {e.printStackTrace();}
    }                                 
    }//GEN-LAST:event_jbtnSearch2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnIssue;
    private javax.swing.JButton jbtnSearch1;
    private javax.swing.JButton jbtnSearch2;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JTextField jtxtAuthor;
    private javax.swing.JTextField jtxtBookID;
    private javax.swing.JTextField jtxtBookYear;
    private javax.swing.JTextField jtxtCampus;
    private javax.swing.JTextField jtxtCourse;
    private javax.swing.JTextField jtxtEdition;
    private javax.swing.JTextField jtxtGuardian;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSem;
    private javax.swing.JTextField jtxtStock;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtTitle;
    private javax.swing.JTextField jtxtYear;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("delivering.png")));
    }
}
