/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;



public class newstudent_frame extends javax.swing.JFrame {
    
   
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public newstudent_frame() {
        setIcon();
        initComponents();
        conn = DBConnect.ConnecrDb();
        setTitle("Add Student");
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtCampus = new javax.swing.JTextField();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtGuardian = new javax.swing.JTextField();
        jbtnRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtCourse = new javax.swing.JTextField();
        jcomboYear = new javax.swing.JComboBox<>();
        jcomboSem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 30, 117));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 209, 18));
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 209, 18));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 74, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 209, 18));
        jLabel3.setText("Guardian");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 209, 18));
        jLabel4.setText("Course");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 74, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 209, 18));
        jLabel5.setText("Campus");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 90, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 209, 18));
        jLabel6.setText("Year");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 74, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 209, 18));
        jLabel7.setText("Semester");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 91, 30));

        jtxtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtName.setPreferredSize(new java.awt.Dimension(15, 20));
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 210, 30));

        jtxtCampus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtCampus.setPreferredSize(new java.awt.Dimension(15, 20));
        jtxtCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCampusActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 210, 30));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtStudentID.setPreferredSize(new java.awt.Dimension(15, 20));
        jtxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 210, 30));

        jtxtGuardian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtGuardian.setPreferredSize(new java.awt.Dimension(15, 20));
        jtxtGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGuardianActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtGuardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 210, 30));

        jbtnRegister.setBackground(new java.awt.Color(255, 209, 18));
        jbtnRegister.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnRegister.setForeground(new java.awt.Color(255, 4, 0));
        jbtnRegister.setText("REGISTER");
        jbtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 190, 70));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 209, 18));
        jLabel8.setText("Student Registration...");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jtxtCourse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtCourse.setPreferredSize(new java.awt.Dimension(15, 20));
        jtxtCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCourseActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 210, 30));

        jcomboYear.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jcomboYear.setForeground(new java.awt.Color(255, 209, 18));
        jcomboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Year-", "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        jcomboYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jcomboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 190, 30));

        jcomboSem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jcomboSem.setForeground(new java.awt.Color(255, 209, 18));
        jcomboSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Semester-", "1st Semester", "2nd Semester" }));
        jcomboSem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jcomboSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 190, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "StudentID", "Name", "Guardian", "Course", "Campus", "Year", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 980, 200));

        jButton1.setBackground(new java.awt.Color(255, 209, 18));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/BACK.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 38, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCampusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCampusActionPerformed

    private void jtxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentIDActionPerformed

    private void jtxtGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGuardianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGuardianActionPerformed

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed

        if ( jtxtStudentID.getText().isEmpty() || jtxtStudentID.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "The fields cannot be left blank.", "Message" , JOptionPane.INFORMATION_MESSAGE);
             }
        else{
        try{
        String sql = "INSERT INTO student"
                + "(StudentID, Name, Guardian, Course, Campus, Year, Semester)"
                + "VALUES (?,?,?,?,?,?,?)";
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management_system","root","root");
        pst = conn.prepareStatement(sql);
        pst.setString(1, jtxtStudentID.getText());
        pst.setString(2, jtxtName.getText());
        pst.setString(3, jtxtGuardian.getText());
        pst.setString(4, jtxtCourse.getText());
        pst.setString(5, jtxtCampus.getText());
        pst.setString(6, (String) jcomboYear.getSelectedItem());
        pst.setString(7, (String) jcomboSem.getSelectedItem());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Student Registered!");
        
       jtxtName.setText("");
       jtxtCampus.setText("");
       jtxtStudentID.setText("");
       jtxtGuardian.setText("");
       jtxtCourse.setText("");
       jcomboYear.setSelectedItem("-Select Year-");
       jcomboSem.setSelectedItem("-Select Semester-");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
     }
         try{
            PreparedStatement ps = conn.prepareStatement("select * from student;");
            ResultSet set = ps.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(set));
        }
        catch(Exception e){e.printStackTrace();}
           
       
    }//GEN-LAST:event_jbtnRegisterActionPerformed
    }
    private void jtxtCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCourseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main_frame ob = new main_frame();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudent_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudent_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudent_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudent_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudent_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JComboBox<String> jcomboSem;
    private javax.swing.JComboBox<String> jcomboYear;
    private javax.swing.JTextField jtxtCampus;
    private javax.swing.JTextField jtxtCourse;
    private javax.swing.JTextField jtxtGuardian;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtStudentID;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("add.png")));
    }
}
